# Generated by Django 5.1 on 2024-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmanager',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
