# Generated by Django 5.1 on 2024-09-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_article_section_category_sections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sections',
            new_name='section',
        ),
    ]
