# Generated by Django 5.1 on 2024-10-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_agent_is_active_agentgroup_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentgroup',
            unique_together={('name', 'section')},
        ),
    ]
