# Generated by Django 5.1 on 2024-09-15 18:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sections_category_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
