# Generated by Django 5.1 on 2024-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_agentgroup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('name', 'region', 'phone', 'group')},
        ),
        migrations.AddField(
            model_name='agent',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='number',
        ),
    ]
