# Generated by Django 5.1 on 2024-09-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
