# Generated by Django 5.1 on 2024-09-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ManyToManyField(to='main.section'),
        ),
    ]
