# Generated by Django 5.1 on 2024-09-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_article_section_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticle',
            name='section',
            field=models.ManyToManyField(to='main.section'),
        ),
    ]
