# Generated by Django 5.1 on 2024-09-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subarticle_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subarticle',
            name='section',
        ),
        migrations.AddField(
            model_name='subarticle',
            name='section',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
