# Generated by Django 5.1 on 2024-09-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_subarticle_section_subarticle_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticle',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
